// ── Stripe Client ──────────────────────────────────────────────────────────
// This file is generated by the Stripe integration after connecting your account.
// Until connected, all Stripe calls will throw "Stripe not yet connected."
// After connecting, this file will be replaced with your actual credentials.

export async function getUncachableStripeClient(): Promise<any> {
  throw new Error(
    "Stripe not yet connected. Please connect your Stripe account in the Integrations panel."
  );
}

export async function getStripeSync(): Promise<any> {
  throw new Error(
    "Stripe not yet connected. Please connect your Stripe account in the Integrations panel."
  );
}
